# needed for python >= 3.6
sudo: required
dist: xenial
cache: pip
# ---
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
script:
  # pytype does not work under 3.8 yet, and we only need to typecheck one 3.x version
  - |
    if (( $(bc -l <<< "${TRAVIS_PYTHON_VERSION} == 3.7") )); then
      pytype -d import-error hypothesis_grammar/;
    fi
  - pytest -v tests/
